version: '3'

env:
  DOCKER_GATEWAY_HOST:
    sh: hostname -I | awk '{print $1}' # TODO: What's a stable way of acquiring this info across the majority of distros/computers??

tasks:
  start:
    desc: "Start Bionic GPT (interactive shell with live log trace)."
    preconditions:
      - pgrep -f ollama
    interactive: true
    cmds:
      - |
        echo "Docker gateway host is $DOCKER_GATEWAY_HOST"
        docker-compose -f docker-compose.yml up

  start-daemon:
    desc: "Start Bionic GPT (daemon mode; background task)."
    preconditions:
      - pgrep -f ollama
    interactive: true
    cmds:
      - |
        echo "Docker gateway host is $DOCKER_GATEWAY_HOST"
        docker-compose -f docker-compose.yml up -d

  stop-daemon:
    desc: "Start Bionic GPT (daemon mode; background task)."
    interactive: true
    cmds:
      - |
        docker-compose -f docker-compose.yml down
